# Generated by Django 5.0.4 on 2024-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_remove_useraccount_email_alter_useraccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=255, unique=True),
        ),
    ]
