# Generated by Django 5.0.4 on 2024-05-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_useraccount_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email',
        ),
    ]
