# Generated by Django 5.0.4 on 2024-05-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_name', models.CharField(max_length=100)),
                ('county_no', models.IntegerField(primary_key=True, serialize=False)),
                ('county_price', models.DecimalField(max_digits=6, decimal_places=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_label', models.CharField(max_length=100)),
            ],
        ),
    ]
