# Generated by Django 5.0.4 on 2024-05-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='county',
            name='county_price',
        ),
        migrations.RemoveField(
            model_name='projecttype',
            name='project_label',
        ),
        migrations.AddField(
            model_name='projecttype',
            name='project_name',
            field=models.CharField(default='Project Name', max_length=100),
        ),
        migrations.AddField(
            model_name='projecttype',
            name='project_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
