# Generated by Django 5.0.4 on 2024-05-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_county_county_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttype',
            name='county',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculator.county'),
            preserve_default=False,
        ),
    ]
