# Generated by Django 5.0.4 on 2024-05-07 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_projecttype_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttype',
            name='county',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='calculator.county'),
        ),
    ]
